 name: Backend - Build & Deploy Space Backend Email Service

 on:
   workflow_dispatch:
   push:
     branches:
       - master
       - develop
     paths:                               #  for any changes in any of these files: will build and deploy
       - '**.py'
       - '**.html'
       - 'Dockerfile'
       - 'pyproject.toml'

 jobs:
   email-service:
     uses: Space-by-CHI/chi-infra-workflows/.github/workflows/k8s-build-deploy.yml@chore/url-change
     secrets: inherit
     with:
       dockerfile_path: "Dockerfile"
       service_name: "email"
       docker_context: "."
       argocd_folder: './space/backend/email'